name: Java CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Unit Tests
      run: mvn test

    - name: Run Integration Tests
      run: mvn verify

    - name: Static Code Analysis with Qodana
      uses: JetBrains/qodana-action@v2.1
      with:
        project-dir: ${{ github.workspace }}
